# Generated by Django 4.2.14 on 2024-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(help_text="Please upload your sound recording here.<br> If you're using Android or iOS and require help, please <a href=''>see the help guides</a>", upload_to='researchdata/sounds/')),
                ('location', models.CharField(blank=True, help_text='Please provide some brief information about where you made the recording - e.g. a suburb in Kyiv, etc.', max_length=255, null=True)),
                ('recording_date', models.DateField(blank=True, help_text='Please provide the date that the sound recording was produced', null=True, verbose_name='date of recording')),
                ('recording_time', models.TimeField(blank=True, help_text='Please provide the time that the sound recording was produced (approximate hour, if exact time not known)', null=True, verbose_name='time of recording')),
                ('description', models.TextField(blank=True, help_text='Please provide any important information about the recording - e.g. the main sounds that it captures, your feelings about the recording, etc.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
